### ISSUE TITLE
Fix Pursuit

### ISSUE THREAD

**Issue by Ptival** [LukaJCB/purescript-rxps#2]
Hey, I'm looking forward to using this library, but this is kinda weird. On Pursuit, there are multiple occurrences, under the names `purescript-rxps` and `purescript-rx-observable`.

It seems you are favoring the former, was the latter the old name of the package?

Is it possible to remove the other one entirely from Pursuit?

**Comment by LukaJCB** [comment]
Yes that's correct :)
I'm looking into deleting the old one, but I'm not sure if it's possible 🤔
