### ISSUE TITLE
Dependencies are out of date

### ISSUE THREAD

**Issue by liam-cb** [LukaJCB/purescript-rxps#4]
Installing this causes conflicts with newer purescript libraries including the newest purescript-prelude. Tried to take a stab at updating it but I don't know bower very well.

**Comment by LukaJCB** [comment]
Unfortunately, due to time constraints, I'm not really maintaining this very much, I'd be happy to give you merge rights if you'd like :)

**Comment by waynevanson** [comment]
Closed by #9
