### ISSUE TITLE
Why <Observable a> is implemented in terms of <ObservableT Identity> ?

### ISSUE THREAD

**Issue by Vikasg7** [LukaJCB/purescript-rxps#8]
Hi,  
I am new to Purescript. As I was learning about Monad Transformers Stack, how many different types of Monad Transformers are there and how they are implemented,  I was going through the code and felt you have over-implemented the `Observable a` by declaring it in terms of `ObservableT Identity` as it could just be equal to `ObservableImpl a`. You are using a lot of `unwrap***` functions which I felt was unnecessary and a performance burden coz if you look at the [implementation of MaybeT](https://github.com/purescript/purescript-transformers/blob/v4.2.0/src/Control/Monad/Maybe/Trans.purs). It's just wrapping already defined `Maybe a` type (which in this case is `ObservableImpl a`). So propose to rename `ObseravbleImpl a` to `Observable a` and take out all the unnecessary code. Also, you should also add the instances for `MonadState, MonadTell, MonadEffect and so on` as done in the implementation of `MaybeT` (if they make sense for ObservableT).

**Comment by waynevanson** [comment]
Thanks for the question and issue. 

> over-implemented the `Observable a` by declaring it in terms of `ObservableT Identity` as it could just be equal to `ObservableImpl a`.

1. It's much more convenient to use the monad transformer like we currently have.
    - The transformer means we can derive `ObservableT a` from `a`. Otherwise we'd have to write new functions every time we define a new `newtype`.
2. There's very little impact on performance.

Am I missing something? If so would you be able to elaborate? Otherwise we can close this issue.
